### ISSUE TITLE
Debugger / Monitor

### ISSUE THREAD

**Issue by nopjmp** [hsoft/collapseos#9] opened 2019-10-09 03:02 UTC
I would like to start out that I'm very impressed by this project.

I was curious if there is a way to debug programs (i.e. monitor mode) built into the kernel. This would make it easier in a "collapse" situation when it may be difficult to find documentation. Source Code is enough but sometimes a debugger would be helpful to poke around in memory

I'm currently working on acquiring some test hardware to see if I could assist but I'm still working on learning Z80 assembly.

**Comment by lmamakos** [comment] 2019-10-10 20:57
Embedding a small FORTH kernel into the platform gives you a great debugging tool.  There's a related issue regarding FORTH.

**Comment by hsoft** [comment] 2019-10-31 01:56
Closing because the request is too vague (or a duplicate of #4). Please re-open if you have a specific suggestion to improve debugging capabilities.

**Closed by hsoft** 2019-10-31 01:56 UTC
